### PR TITLE
Fix issue caused by new script cache in 1.23.1

### LINKED ISSUE #46: Streamlit 1.23.1 breaking rerun on changes for pages
After upgrading to 1.23.1 of Streamlit, all of a sudden any pages do not capture changes when rerunning after saving.

In some cases it notifies that the file has changed, but rerunning the page does not reflect the updated report.

Simple replication:

- install st_pages 0.4.1 and streamlit 1.22.0 for an app with 1 subpage
- confirm that changing subpage (e.g. st.write) updates when changed
- update to streamlit 1.23.1
- the subpage now no longer will update

Not sure where this bug actually lies. But given a "normal" streamlit multipage app seems OK, is it something how st_pages registers the pages?

### PR DESCRIPTION
**Pull request by mfriedy**
Fixes #46 

- Set script_path to absolute script path, as this seems to be more consistent with that is done normally in streamlit (and is needed for the sourcewatcher to register it correctly?)
- re-register the scriptwatcher that the scriptcache uses, to pick up the pages added by st_pages

@blackary  - I am not sure how correct it is to directly interact with the runtime like this. But it seems to fix the issue :)

### CODE REVIEW

**Comment by mfriedy** [comment]
Hi @blackary any chance you can look at this?

**Comment by blackary** [comment]
@mfriedy Yes, sorry it's taken a while, but I will take a look at this. I've been doing some work to get tests fixed in #45

**Comment by blackary** [comment]
@mfriedy I had trouble getting the fix to work without adding a tiny sleep. After that it seemed to work fine. Now making sure it still works with different versions.

**Comment by blackary** [comment]
I can get the tests to pass locally, but am having trouble getting them to pass on github actions so far :/

**Comment by mfriedy** [comment]
That's really weird re the sleep, no idea. Is it something to do with accessing the runtime directly?

**Review by blackary — APPROVED** [review]
THANK YOU so much for this improvement -- so sorry it took so long to get everything passing

**Pull request merged**
