### PR TITLE
BREAKING CHANGE: Convert st-pages to a thin wrapper around new st.navigation

### LINKED ISSUE #12: Support bootstrap icons

### LINKED ISSUE #25: "The page that you have requested does not seem to exist. Running the app's main page."
"Page not found. The page that you have requested does not seem to exist. Running the app's main page."
I constantly get this error on start up 
Is there a way to avoid it?

### LINKED ISSUE #43: st.header() anchor links do not work
Hi.  I just noticed that the #anchor links included with, say, st.header() do not work on st-pages pages.  Instead one just gets redirected to the root/main page.

I double checked and anchor links in regular Streamlit pages/foo do work.  So, I believe the issue is specific to st-pages.

### LINKED ISSUE #52: Streamlit 1.24.1 scrambling page order
Possibly related: https://github.com/blackary/st_pages/issues/46

I am too facing the problem with combination of latest `st_pages` and `streamlit` `1.24.1`.

In my case the order of pages is scrambled for whatever reason.

For now I just experimentally figured out that `0.4.1` and `1.24.0` combo seem to work.

As far as I get, the problem is along these lines:
```
def _show_pages(pages: list[Page]):
    current_pages: dict[str, dict[str, str | bool]] = get_pages("")  # type: ignore
    if set(current_pages.keys()) == set(p.page_hash for p in pages):
        return
```
In the latest version `streamlit.source_util.get_pages("")` seem to return **unordered** list of pages, and I suspect this is what causes the problem.

### LINKED ISSUE #53: Same script for multiple pages
It would be useful to allow the same script to be used as the file for multiple pages.
This can be enabled by adding the page name during the MD5 hash computation.

The following script can then be used to determine which page reference is being requested:
```
from streamlit.runtime.scriptrunner import get_script_run_ctx
from streamlit.source_util import get_pages


def get_current_page():
    pages = get_pages("")
    ctx = get_script_run_ctx()
    if ctx is not None:
        try:
            return pages[ctx.page_script_hash]
        except KeyError:
            pass

    return None
```

### LINKED ISSUE #67: Several Issues
Note: I am using the page_switch() module at the same time. 

I am getting an error often (not always) that results in the page loading twice due to an exception. The exception is shown below. 
This happens when using the pages menu in the sidebar. Click back and forth to the various pages repeatedly. cause exceptions. Clicking a subpage will result in the error below, which starts in the current home page called Site_Select. 

Traceback (most recent call last):
  File "/Users/jack/miniconda3/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/Users/jack/jmautogpt/masterpro.ai.dashboard/ultimate-flask-front-end-2.1/steamlitapp/pages/2_dashboard.py", line 5, in <module>
    import Site_Select
  File "/Users/jack/jmautogpt/masterpro.ai.dashboard/ultimate-flask-front-end-2.1/steamlitapp/Site_Select.py", line 9, in <module>
    ****show_pages_from_config(".streamlit/pages.toml")****
  File "/Users/jack/miniconda3/lib/python3.9/site-packages/streamlit/runtime/metrics_util.py", line 367, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/Users/jack/miniconda3/lib/python3.9/site-packages/st_pages/__init__.py", line 295, in _show_pages_from_config
    show_pages(pages)
  File "/Users/jack/miniconda3/lib/python3.9/site-packages/streamlit/runtime/metrics_util.py", line 367, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/Users/jack/miniconda3/lib/python3.9/site-packages/st_pages/__init__.py", line 233, in _show_pages
    **first_page_hash = list(current_pages.keys())[0]**
IndexError: list index out of range

If I restart the application and click back and forth between the Home page (Site_Select) and the first subpage I can get this error pop up **Cannot read properties of undefined (reading 'pageScriptHash')**

There are bugs in this module that take work to find. I can move back and forth from page to page and eventually get the error above. This is a popup error message, and the command line has no stack trace. 

Thanks - Jack

### LINKED ISSUE #69: Bad message format Cannot read properties of undefined (reading 'pageScriptHash')
When I am interacting with a page (therefore causing reruns) and the icons for the pages are appearing normally (there's times that they don't appear) I sometimes get the message on streamlit:

> **Bad message format**
> Cannot read properties of undefined (reading 'pageScriptHash')

It will also sometimes if I am not in the main page redirect you to a page _http://localhost:8501/undefined_ that doesn't exist. If i enter that url in the browser it gives "page not found". 
if you keep interacting with this ghost page it will go back to the real one eventually. But in these changes back and forth from the ghost page all the session_state is lost  which is pretty annoying and makes the app unusable.

The bug though disappears if I use version` st-pages==0.4.1` and I think it's related to the component `st_aggrid` because only when I have an AgGrid that the ghost page and session state delete occurs. For the other pages it's only the message `Bad message format Cannot read properties of undefined (reading 'pageScriptHash')`

This is related to this post I made in the streamlit forums:
https://discuss.streamlit.io/t/using-aggrid-sometimes-changes-the-page-to-undefined-reseting-the-session-state/50090

### LINKED ISSUE #70: How to define custom url for each page ?
Hi,
  I would like to define custom url for each page.

### LINKED ISSUE #75: Hot loading was broken
After change code, it was not re-loading to take effect and have to stop streamlit server and re-start.
Checked on streamlit v1.28

### LINKED ISSUE #90: st_pages config in .streamlit/pages.toml doesn't work on Streamlit Cloud Environment
I'm getting:

```
2024-01-09 05:21:27.524 Uncaught app exception

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script

    exec(code, module.__dict__)

  File "/mount/src/streamlit-deployment-test/main_page.py", line 2, in <module>

    from st_pages import show_pages_from_config, add_page_title

ModuleNotFoundError: No module named 'st_pages'

2024-01-09 05:21:27.652 503 GET /script-health-check (10.12.146.161) 130.20ms
```

I've added the package in my `requirements.txt`. Not sure why Streamlit Cloud isn't able to import `st_pages`

### PR DESCRIPTION
**Pull request by blackary**
# Why?

st_pages was always created as an experimental way to improve on streamlit's built-in multipage app support. I wanted to have a way to specify the pages in my app in any order, with any icons, and with sections, without having to worry about where the files were located, or what they were named.

As of [streamlit 1.36.0](https://docs.streamlit.io/develop/quick-reference/release-notes#version-1360), these are all possible with native streamlit functions (and without the need to hackily manipulate internal cached dictionaries the way st-pages has always previously worked). To be honest, this makes me *so happy*, because these changes were partly inspired by the way st-pages works, and I'm so glad that more people like me will get to have this level of control over their page navigation without any 3rd-party tools needed.

There are still a few useful things that this library does that are small improvements on top of st.navigation:
* Reading pages directly from toml
* Adding the page title to a page in a standardized way

But, switching to simply being a lite wrapper on top of st.navigation comes with the following benefits (in no particular order):
* Supporting material icons (closes #12)
* Using the same page or function for multiple pages (closes #53)
* Easy support for custom url fragments (closes #70)
* Fixing flaky cases and bugs like 
	* closes #67
	* closes #52
	* closes #75
	* closes #25
	* closes #90
	* closes #69
	* closes #43

# The Trade-off

The trade-off is that this means that st-pages 1.0 will **NOT** be a drop-in replacement for earlier versions of st-pages, but will be a **VERY**-breaking change:
* It will require you to refactor your app into one page that sets up the navigation and common code (e.g. [streamlit_app.py](example_app/streamlit_app.py))
* Some of the old functions are gone (e.g. add_indendation), mostly because they are now done natively

If it was easy to keep the same basic API but using native functions, I probably would have, but, frankly, I couldn't figure out a way to make it work.

I'm very open to feedback on this from users of st-pages, but I'm fairly confident that this is the way I'm going to go.

### CODE REVIEW

**Comment by sfc-gh-trichards** [comment]
I'm a very big fan of this, because:
- anyone using the latest version of streamlit basically get a built in version of st-pages (win!)
- anyone who wants some nice extra features can still use st-pages pretty easily
- anyone who is not updated to streamlit 1.36+ can just not upgrade

**Comment by Sairam90** [comment]
@blackary Any idea by when the lib will be updated with these changes?

**Comment by blackary** [comment]
@Sairam90 done :)

**Comment by Sairam90** [comment]
Thank you!..Will try it out !

**Comment by Sairam90** [comment]
@blackary I am not sure if I am reconstruct the section page structure without the in_section attribute
I was using this to identify
1.pages which are not under any sections
2.find sections where all pages are hidden and hide the section as well in this case

Do you think this can be done with the exisitng attributes ?

**Comment by blackary** [comment]
@Sairam90 you can get the first one from `get_nav_from_toml` and look for the pages that are under the entry `""`, which means no section. 
For the second one, you can use the same function, and look for sections that have an empty list of pages.

The structure returned from that function should be something like that 
```python
{
	"": [st.Page("home.py", title="Home")],
	"Section1": [st.Page("page2.py", title="Page2")],
	"Section2": [],
}
```

**Comment by Sairam90** [comment]
Ah,great,thanks again !🙂

**Comment by Sairam90** [comment]
Hey @blackary - If there is a page which is not part of a section between two other sections it is added to the section above it  

 - For the below sample page config , I "lone_page2" is added as a page in section3

toml 
[sample_section_page.txt](https://github.com/user-attachments/files/16411962/sample_section_page.txt)
result 
[result_get_nav_from_toml.txt](https://github.com/user-attachments/files/16412194/result_get_nav_from_toml.txt)

**Comment by blackary** [comment]
@Sairam90 Currently the only way to have a page not in a section is to have it at the beginning

**Comment by Sairam90** [comment]
cool..thank you!

**Comment by lonbaw** [comment]
Can you take a look at this question?
https://github.com/blackary/st_pages/issues/103

**Pull request merged**
